###
# Create a admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Bossman",
    "email":"admin@gmail.com",
    "password":"12345",
    "confPassword": "12345",
    "role": "admin"
}

###
# Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe 2",
    "email": "john2@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}


###
# get all Users
GET http://localhost:5000/users

###
# get Single User
GET http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c


###
# Update a user
PATCH http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c
Content-Type: application/json

{
    "name": "John Updated",
    "email": "john@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
# Delete a user
DELETE http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c

###
# Login a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"john2@gmail.com",
    "password":"12345"
}

###
# Login as an admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345"
}

###
# Get User through session check
GET http://localhost:5000/me

###
# Logout
DELETE http://localhost:5000/logout

###
# get all tickets
GET http://localhost:5000/tickets

###
# get single ticket
GET http://localhost:5000/tickets/c8f45a34-0b2d-4002-9b2a-a9e9055444eb

###
# Create a ticket
POST http://localhost:5000/tickets
Content-Type: application/json

{
    "subject": "Test 1",
    "description": "Test for resolving the ticket",
}

###
# Update a ticket
PATCH http://localhost:5000/tickets/6bc94336-1e03-43e4-8e86-63daa0d964c4
Content-Type: application/json

{
    "subject": "Test 1 Updated",
    "description": "Test for resolving the ticket [Updated]",
}

###
# Delete a ticket
# DELETE http://localhost:5000/tickets/c8f45a34-0b2d-4002-9b2a-a9e9055444eb Example
DELETE http://localhost:5000/tickets/<:ticket's uuid>