# Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe 3",
    "email": "john3@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}


###
# get all Users
GET http://localhost:5000/users

###
# get Single User
GET http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c


###
# Update a user
PATCH http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c
Content-Type: application/json

{
    "name": "John Updated",
    "email": "john@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
# Delete a user
DELETE http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c

###
# Login a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"john2@gmail.com",
    "password":"12345"
}

###
# Login as an admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345"
}

###
# Get User through session check
GET http://localhost:5000/me

###
# Logout
DELETE http://localhost:5000/logout
