# Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe 3",
    "email": "john3@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}


###
# get all Users
GET http://localhost:5000/users

###
# get Single User
GET http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c


###
# Update a user
PATCH http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c
Content-Type: application/json

{
    "name": "John Updated",
    "email": "john@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
# Delete a user
DELETE http://localhost:5000/users/b5d2e24e-1d97-4757-836d-df019dcf8f7c

###
# Login a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"john2@gmail.com",
    "password":"12345"
}

###
# Login as an admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345"
}

###
# Get User through session check
GET http://localhost:5000/me

###
# Logout
DELETE http://localhost:5000/logout

###
# get all products
GET http://localhost:5000/products

###
# get single products
GET http://localhost:5000/products/c8f45a34-0b2d-4002-9b2a-a9e9055444eb

###
# Create a product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 2",
    "price": 200
}

###
# Update a product
PATCH http://localhost:5000/products/6bc94336-1e03-43e4-8e86-63daa0d964c4
Content-Type: application/json

{
    "name": "Product Updated",
    "price": 97493
}

###
# Delete a product
DELETE http://localhost:5000/products/c8f45a34-0b2d-4002-9b2a-a9e9055444eb


###
# get all tickets
GET http://localhost:5000/tickets

###
# get single ticket
GET http://localhost:5000/tickets/c8f45a34-0b2d-4002-9b2a-a9e9055444eb

###
# Create a ticket
POST http://localhost:5000/tickets
Content-Type: application/json

{
    "name": "Product 2",
    "price": 200
}

###
# Update a ticket
PATCH http://localhost:5000/tickets/6bc94336-1e03-43e4-8e86-63daa0d964c4
Content-Type: application/json

{
    "name": "Product Updated",
    "price": 97493
}

###
# Delete a ticket
DELETE http://localhost:5000/tickets/c8f45a34-0b2d-4002-9b2a-a9e9055444eb